spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/gamelist
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=never
jwt.secret= MinhaChaveSecretaMuitoLonga1234567890
jwt.expiration=604800000
server.servlet.context-path=/api
